package com.das.consultation.enums;

/**
 * created by jun on 2020/9/22
 * describe:数据校验类型枚举
 * version 1.0
 */
public enum RangeEnum {
    PERSONNEL_TYPE,APP_MODE,PAY_ACC_TYPE,STD_EVENT_TYPE,CARD_TYPE,PAY_TYPE,APP_PAY_TYPE,RESOURCE_MANAGER_TYPE,PATIENT_CARD_NEED
    ,IS_IMPORTANT,ORDER_SCOPE,PATIAPPLYTYPE,ABNORMAL,ISYUYUE,YUYUEUSERTYPE,HAS_NO,PAY_STATE,MZ_TYPE,PAY_TYPE_DCT,PAY_CHANNEL,APP_METHOD,BUSINESS_TYPE,STATE,DATA_SOURCE
    ,CHECK_TYPE,YUYUE_FROM,ORDER_STATUS
}
